"""Generator of a synthetic scene in the binary COLMAP sparse format.

IMPORTANT (a project constitution requirement, honesty of the result):
    This scene checks ONLY file formats and geometric operations
    (writing/reading `cameras.bin`, `images.bin`, `points3D.bin`, the world_to_camera pose
    convention, recomputation of camera centres, consistency of tracks).
    It does NOT prove and cannot prove the quality of a real reconstruction:
    there are no images, no feature detector and no optimization here —
    all poses and points are defined analytically.

What is generated
-----------------
- N cameras evenly placed on a circle of radius R around the origin
  (at height `--height`), all looking at the scene centre (0, 0, 0).
  Optional distortions (arc, height jitter, roll jitter, vertical wave, whole-scene tilt and
  offset) imitate a handheld orbit in an arbitrary frame; `expected.json` then records
  `true_up_world` and `true_object_center` in the written frame.
- The camera model is **PINHOLE** (`model_id = 1`, parameters `fx, fy, cx, cy`).
  It was chosen over SIMPLE_PINHOLE so that tests see separate fx/fy and
  catch swapped axes. All cameras share one `camera_id = 1`.
- A cloud of coloured points on the surface of a cube at the scene centre; the colour is
  deterministically derived from the point coordinates (no RNG involved).
- 2D observations are obtained by an honest pinhole projection of the 3D points into each
  camera; only points in front of the camera and inside the frame are kept. Tracks in
  `points3D.bin` refer to real indices of the 2D points of the corresponding images.
  Self-occlusion of the cube is NOT modelled (points on the far face are "visible" too) —
  this is immaterial for checking formats and track consistency.

Pose convention
---------------
COLMAP stores **world_to_camera**: `x_cam = R @ x_world + t`, where `R` is obtained from the
quaternion `(qw, qx, qy, qz)`. Camera centre in the world: `C = -R.T @ t`.
Camera axes: x — right, y — down, z — forward (along the viewing direction).

Image names
-----------
The project's frame format: `NNNN_SSSSSS.jpg` (for example `0000_000012.jpg`), where
NNNN is the sequence number among the selected frames, SSSSSS is the frame index in the video.

Determinism
-----------
The only source of randomness is `numpy.random.default_rng(seed)`. A repeated
run with the same `--seed` and the same parameters gives byte-identical files.

Usage
-----
    python assets/synthetic/make_scene.py --out <dir> [--cameras N] [--points M] [--seed S]

Creates `<dir>/sparse/{cameras,images,points3D}.bin` and `<dir>/expected.json`
with the reference camera centres, poses and parameters — for comparison in tests.
"""

from __future__ import annotations

import argparse
import json
import struct
from dataclasses import dataclass
from pathlib import Path

import numpy as np

# COLMAP camera model identifiers (src/colmap/sensor/models.h).
CAMERA_MODEL_SIMPLE_PINHOLE = 0
CAMERA_MODEL_PINHOLE = 1

# Marker "the 2D point has no corresponding 3D point" in images.bin.
INVALID_POINT3D_ID = 2**64 - 1

CAMERA_ID = 1


@dataclass(frozen=True)
class SceneParams:
    """Parameters of the synthetic scene. Everything that affects the bytes on disk."""

    num_cameras: int = 12
    num_points: int = 500
    seed: int = 0
    radius: float = 3.0
    height: float = 1.0
    cube_half_size: float = 0.5
    width: int = 640
    height_px: int = 480
    fx: float = 500.0
    fy: float = 520.0
    # Image names. Empty — generated by the rule NNNN_SSSSSS.jpg. Given — taken as is:
    # this way the scene can be fitted to the frame names of a specific run and result
    # ingest can be checked without forging frames.json.
    image_names: tuple[str, ...] = ()
    # Distortions imitating a handheld phone orbit and a VGGT reconstruction. The scene is built
    # in a canonical frame (up = +Z, object at the origin); the last two are then applied to the
    # WHOLE scene as one rigid transform. Defaults reproduce the undistorted scene exactly.
    arc_deg: float = 360.0  # cameras span only this arc of the circle
    height_jitter: float = 0.0  # std-dev of random per-camera height offsets
    roll_jitter_deg: float = 0.0  # std-dev of per-camera roll about the optical axis
    tilt_deg: float = 0.0  # rotation of the whole scene about `tilt_axis`
    tilt_axis: tuple[float, float, float] = (1.0, 0.0, 0.0)
    offset: tuple[float, float, float] = (0.0, 0.0, 0.0)  # translation after the tilt
    non_planar: float = 0.0  # amplitude A of the vertical wave: height += A * sin(2 * phi)


def axis_angle_rotation(axis: np.ndarray, angle_rad: float) -> np.ndarray:
    """Rotation matrix about `axis` (normalized internally) by `angle_rad` (Rodrigues)."""
    axis = np.asarray(axis, dtype=np.float64)
    norm = float(np.linalg.norm(axis))
    if norm == 0.0:
        raise ValueError("The rotation axis must be non-zero")
    x, y, z = axis / norm
    skew = np.array([[0.0, -z, y], [z, 0.0, -x], [-y, x, 0.0]])
    return np.eye(3) + np.sin(angle_rad) * skew + (1.0 - np.cos(angle_rad)) * (skew @ skew)


def global_transform(params: SceneParams) -> tuple[np.ndarray, np.ndarray]:
    """Rigid transform `x' = G @ x + o` from the canonical frame to the written frame."""
    if params.tilt_deg != 0.0:
        rot = axis_angle_rotation(np.array(params.tilt_axis), np.deg2rad(params.tilt_deg))
    else:
        rot = np.eye(3)
    return rot, np.array(params.offset, dtype=np.float64)


def is_identity_transform(params: SceneParams) -> bool:
    """True when the global transform does nothing (keeps default output byte-identical)."""
    return params.tilt_deg == 0.0 and all(v == 0.0 for v in params.offset)


def look_at_rotation(center: np.ndarray, target: np.ndarray) -> np.ndarray:
    """World_to_camera rotation matrix for a camera at `center` looking at `target`.

    The rows of the result are the camera axes in world coordinates: x (right), y (down),
    z (forward). The world "up" is +Z; it must not be collinear with the viewing
    direction, otherwise the basis degenerates.
    """
    forward = target - center
    norm = float(np.linalg.norm(forward))
    if norm == 0.0:
        raise ValueError("The camera centre coincides with the look-at target")
    forward = forward / norm

    world_up = np.array([0.0, 0.0, 1.0])
    right = np.cross(forward, world_up)
    right_norm = float(np.linalg.norm(right))
    if right_norm < 1e-9:
        raise ValueError(
            "The viewing direction is collinear with the world up: the basis is degenerate"
        )
    right = right / right_norm
    down = np.cross(forward, right)

    return np.stack([right, down, forward], axis=0)


def rotation_to_quaternion(rot: np.ndarray) -> np.ndarray:
    """Quaternion (qw, qx, qy, qz) from a rotation matrix.

    A numerically stable branching Shepperd formula is used. The quaternion sign is
    normalized (`qw >= 0`), otherwise the same pose could be written as two
    different sets of bytes.
    """
    trace = float(rot[0, 0] + rot[1, 1] + rot[2, 2])
    if trace > 0.0:
        s = np.sqrt(trace + 1.0) * 2.0
        qw = 0.25 * s
        qx = (rot[2, 1] - rot[1, 2]) / s
        qy = (rot[0, 2] - rot[2, 0]) / s
        qz = (rot[1, 0] - rot[0, 1]) / s
    elif rot[0, 0] > rot[1, 1] and rot[0, 0] > rot[2, 2]:
        s = np.sqrt(1.0 + rot[0, 0] - rot[1, 1] - rot[2, 2]) * 2.0
        qw = (rot[2, 1] - rot[1, 2]) / s
        qx = 0.25 * s
        qy = (rot[0, 1] + rot[1, 0]) / s
        qz = (rot[0, 2] + rot[2, 0]) / s
    elif rot[1, 1] > rot[2, 2]:
        s = np.sqrt(1.0 + rot[1, 1] - rot[0, 0] - rot[2, 2]) * 2.0
        qw = (rot[0, 2] - rot[2, 0]) / s
        qx = (rot[0, 1] + rot[1, 0]) / s
        qy = 0.25 * s
        qz = (rot[1, 2] + rot[2, 1]) / s
    else:
        s = np.sqrt(1.0 + rot[2, 2] - rot[0, 0] - rot[1, 1]) * 2.0
        qw = (rot[1, 0] - rot[0, 1]) / s
        qx = (rot[0, 2] + rot[2, 0]) / s
        qy = (rot[1, 2] + rot[2, 1]) / s
        qz = 0.25 * s

    quat = np.array([qw, qx, qy, qz], dtype=np.float64)
    quat = quat / float(np.linalg.norm(quat))
    if quat[0] < 0.0:
        quat = -quat
    return quat


def make_cameras(params: SceneParams) -> list[dict]:
    """Camera poses on a circle around the origin, all looking at the centre.

    Cameras are first built in the canonical frame (up = +Z): arc, height jitter, vertical wave
    and roll are applied there; then the global tilt/offset is applied to the poses.

    Returns a list of descriptions: image_id, file name, quaternion, translation vector and
    the reference camera centre in the world (written frame).
    """
    target = np.zeros(3)
    n = params.num_cameras
    # Independent of the parameter values: draws are always made, so changing one jitter
    # never changes the random values used by the other.
    rng = np.random.default_rng(params.seed)
    height_noise = rng.normal(0.0, 1.0, size=n) * params.height_jitter
    roll_noise = np.deg2rad(rng.normal(0.0, 1.0, size=n) * params.roll_jitter_deg)

    glob_rot, glob_off = global_transform(params)
    identity = is_identity_transform(params)

    poses: list[dict] = []
    for i in range(n):
        if params.arc_deg == 360.0:
            angle = 2.0 * np.pi * i / n
        else:
            # A partial arc: the first and the last camera sit at the arc ends.
            angle = np.deg2rad(params.arc_deg) * (i / (n - 1) if n > 1 else 0.0)
        cam_height = params.height
        if params.height_jitter != 0.0:
            cam_height = cam_height + float(height_noise[i])
        if params.non_planar != 0.0:
            cam_height = cam_height + params.non_planar * float(np.sin(2.0 * angle))
        center = np.array(
            [
                params.radius * np.cos(angle),
                params.radius * np.sin(angle),
                cam_height,
            ]
        )
        rot = look_at_rotation(center, target)
        tvec = -rot @ center
        if params.roll_jitter_deg != 0.0:
            # Rotation about the camera's own optical axis; the centre does not move.
            cos_r, sin_r = float(np.cos(roll_noise[i])), float(np.sin(roll_noise[i]))
            roll_rot = np.array([[cos_r, -sin_r, 0.0], [sin_r, cos_r, 0.0], [0.0, 0.0, 1.0]])
            rot = roll_rot @ rot
            tvec = roll_rot @ tvec
        if not identity:
            # x' = G x + o  =>  R' = R G^T, t' = t - R' o.
            rot = rot @ glob_rot.T
            tvec = tvec - rot @ glob_off
            center = glob_rot @ center + glob_off
        # The frame index in the "source video" — deterministic arithmetic, not RNG.
        source_index = 12 + i * 35
        name = (
            params.image_names[i]
            if i < len(params.image_names)
            else f"{i:04d}_{source_index:06d}.jpg"
        )
        poses.append(
            {
                "image_id": i + 1,
                "name": name,
                "rotation": rot,
                "qvec": rotation_to_quaternion(rot),
                "tvec": tvec,
                "center": center,
            }
        )
    return poses


def make_points(params: SceneParams) -> tuple[np.ndarray, np.ndarray]:
    """Points on the surface of a cube at the scene centre and their colours.

    A point is sampled like this: a cube face is chosen, the two coordinates on the face are
    taken uniformly, the third is pressed to the face. The colour is a deterministic function
    of the coordinates (normalized to 0..255), so only the positions depend on the RNG.
    """
    rng = np.random.default_rng(params.seed)
    half = params.cube_half_size

    faces = rng.integers(0, 6, size=params.num_points)
    uv = rng.uniform(-half, half, size=(params.num_points, 2))

    xyz = np.zeros((params.num_points, 3), dtype=np.float64)
    for idx in range(params.num_points):
        axis = int(faces[idx]) // 2
        sign = 1.0 if int(faces[idx]) % 2 == 0 else -1.0
        other = [a for a in range(3) if a != axis]
        xyz[idx, axis] = sign * half
        xyz[idx, other[0]] = uv[idx, 0]
        xyz[idx, other[1]] = uv[idx, 1]

    # Colour from position: (coordinate + half) / (2 * half) -> 0..255.
    normalized = (xyz + half) / (2.0 * half)
    rgb = np.clip(np.round(normalized * 255.0), 0, 255).astype(np.uint8)

    # The colour is fixed by the canonical position; only then the whole scene is moved.
    if not is_identity_transform(params):
        glob_rot, glob_off = global_transform(params)
        xyz = xyz @ glob_rot.T + glob_off
    return xyz, rgb


def project(
    xyz: np.ndarray,
    rot: np.ndarray,
    tvec: np.ndarray,
    params: SceneParams,
) -> tuple[np.ndarray, np.ndarray]:
    """Pinhole projection of points into the frame. Returns (indices of visible points, pixels).

    A point is considered visible if it is in front of the camera (`z_cam > 0`) and its pixel
    falls inside the frame.
    """
    cx = params.width / 2.0
    cy = params.height_px / 2.0

    cam = xyz @ rot.T + tvec
    in_front = cam[:, 2] > 1e-6
    uv = np.full((xyz.shape[0], 2), np.nan, dtype=np.float64)
    z = cam[in_front, 2]
    uv[in_front, 0] = params.fx * cam[in_front, 0] / z + cx
    uv[in_front, 1] = params.fy * cam[in_front, 1] / z + cy

    inside = (
        in_front
        & (uv[:, 0] >= 0.0)
        & (uv[:, 0] < params.width)
        & (uv[:, 1] >= 0.0)
        & (uv[:, 1] < params.height_px)
    )
    visible = np.nonzero(inside)[0]
    return visible, uv[visible]


def build_observations(
    poses: list[dict],
    xyz: np.ndarray,
    params: SceneParams,
) -> tuple[dict[int, list[tuple[float, float, int]]], dict[int, list[tuple[int, int]]]]:
    """Consistent 2D observations and tracks.

    Returns:
      - `points2d[image_id]` — a list of `(x, y, point3D_id)` in file write order;
      - `tracks[point3D_id]` — a list of `(image_id, point2D_idx)`, where the index points
        to the real position of the observation in the 2D-point list of that image.
    """
    points2d: dict[int, list[tuple[float, float, int]]] = {}
    tracks: dict[int, list[tuple[int, int]]] = {i + 1: [] for i in range(xyz.shape[0])}

    for pose in poses:
        image_id = pose["image_id"]
        visible, uv = project(xyz, pose["rotation"], pose["tvec"], params)
        observations: list[tuple[float, float, int]] = []
        for slot, point_index in enumerate(visible):
            point3d_id = int(point_index) + 1
            observations.append((float(uv[slot, 0]), float(uv[slot, 1]), point3d_id))
            tracks[point3d_id].append((image_id, slot))
        points2d[image_id] = observations

    return points2d, tracks


def write_cameras_bin(path: Path, params: SceneParams) -> None:
    """cameras.bin: uint64 N, then per camera uint32 id, int32 model, uint64 w/h, double params."""
    cx = params.width / 2.0
    cy = params.height_px / 2.0
    with open(path, "wb") as f:
        f.write(struct.pack("<Q", 1))
        f.write(struct.pack("<I", CAMERA_ID))
        f.write(struct.pack("<i", CAMERA_MODEL_PINHOLE))
        f.write(struct.pack("<QQ", params.width, params.height_px))
        f.write(struct.pack("<4d", params.fx, params.fy, cx, cy))


def write_images_bin(
    path: Path,
    poses: list[dict],
    points2d: dict[int, list[tuple[float, float, int]]],
) -> None:
    """images.bin: uint64 N, then per image — id, quaternion, translation, camera_id,
    a name with a terminating null byte and the list of 2D points."""
    with open(path, "wb") as f:
        f.write(struct.pack("<Q", len(poses)))
        for pose in poses:
            f.write(struct.pack("<I", pose["image_id"]))
            f.write(struct.pack("<4d", *(float(v) for v in pose["qvec"])))
            f.write(struct.pack("<3d", *(float(v) for v in pose["tvec"])))
            f.write(struct.pack("<I", CAMERA_ID))
            f.write(pose["name"].encode("utf-8") + b"\x00")

            observations = points2d[pose["image_id"]]
            f.write(struct.pack("<Q", len(observations)))
            for x, y, point3d_id in observations:
                f.write(struct.pack("<2d", x, y))
                f.write(struct.pack("<Q", point3d_id))


def write_points3d_bin(
    path: Path,
    xyz: np.ndarray,
    rgb: np.ndarray,
    tracks: dict[int, list[tuple[int, int]]],
) -> None:
    """points3D.bin: uint64 N, then per point id, xyz, rgb, error, track length and the track."""
    with open(path, "wb") as f:
        f.write(struct.pack("<Q", xyz.shape[0]))
        for index in range(xyz.shape[0]):
            point3d_id = index + 1
            f.write(struct.pack("<Q", point3d_id))
            f.write(struct.pack("<3d", *(float(v) for v in xyz[index])))
            f.write(struct.pack("<3B", *(int(v) for v in rgb[index])))
            # The reprojection error of a synthetic point is exactly zero: the projection is exact.
            f.write(struct.pack("<d", 0.0))
            track = tracks[point3d_id]
            f.write(struct.pack("<Q", len(track)))
            for image_id, point2d_idx in track:
                f.write(struct.pack("<2I", image_id, point2d_idx))


def write_expected_json(
    path: Path,
    params: SceneParams,
    poses: list[dict],
    xyz: np.ndarray,
    points2d: dict[int, list[tuple[float, float, int]]],
) -> None:
    """Reference for tests: parameters, poses, camera centres and observation statistics."""
    glob_rot, glob_off = global_transform(params)
    payload = {
        "note": ("Synthetic scene: checks only formats and geometry, not reconstruction quality."),
        "params": {
            "num_cameras": params.num_cameras,
            "num_points": params.num_points,
            "seed": params.seed,
            "radius": params.radius,
            "height": params.height,
            "cube_half_size": params.cube_half_size,
        },
        "distortion": {
            "arc_deg": params.arc_deg,
            "height_jitter": params.height_jitter,
            "roll_jitter_deg": params.roll_jitter_deg,
            "tilt_deg": params.tilt_deg,
            "tilt_axis": list(params.tilt_axis),
            "offset": list(params.offset),
            "non_planar": params.non_planar,
        },
        # Where the canonical up (+Z) and the canonical origin (object centre) ended up.
        "true_up_world": [float(v) for v in glob_rot @ np.array([0.0, 0.0, 1.0])],
        "true_object_center": [float(v) for v in glob_off],
        "camera": {
            "camera_id": CAMERA_ID,
            "model": "PINHOLE",
            "model_id": CAMERA_MODEL_PINHOLE,
            "width": params.width,
            "height": params.height_px,
            "params": [params.fx, params.fy, params.width / 2.0, params.height_px / 2.0],
        },
        "pose_convention": "world_to_camera: x_cam = R(qvec) @ x_world + tvec; C = -R.T @ tvec",
        "images": [
            {
                "image_id": pose["image_id"],
                "name": pose["name"],
                "qvec": [float(v) for v in pose["qvec"]],
                "tvec": [float(v) for v in pose["tvec"]],
                "center": [float(v) for v in pose["center"]],
                "num_points2D": len(points2d[pose["image_id"]]),
            }
            for pose in poses
        ],
        "points3D": {
            "count": int(xyz.shape[0]),
            "bbox_min": [float(v) for v in xyz.min(axis=0)],
            "bbox_max": [float(v) for v in xyz.max(axis=0)],
            "total_observations": int(sum(len(v) for v in points2d.values())),
        },
    }
    text = json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    path.write_text(text, encoding="utf-8")


def make_scene(out_dir: Path, params: SceneParams) -> dict:
    """Generate the scene and write it into `<out_dir>/sparse` plus `expected.json`."""
    sparse_dir = out_dir / "sparse"
    sparse_dir.mkdir(parents=True, exist_ok=True)

    poses = make_cameras(params)
    xyz, rgb = make_points(params)
    points2d, tracks = build_observations(poses, xyz, params)

    write_cameras_bin(sparse_dir / "cameras.bin", params)
    write_images_bin(sparse_dir / "images.bin", poses, points2d)
    write_points3d_bin(sparse_dir / "points3D.bin", xyz, rgb, tracks)
    write_expected_json(out_dir / "expected.json", params, poses, xyz, points2d)

    return {
        "sparse_dir": sparse_dir,
        "num_images": len(poses),
        "num_points": int(xyz.shape[0]),
        "num_observations": int(sum(len(v) for v in points2d.values())),
    }


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Parsing of command-line arguments."""
    parser = argparse.ArgumentParser(
        description=(
            "Generator of a synthetic COLMAP sparse scene (binary format). "
            "Checks only formats and geometry, not reconstruction quality."
        )
    )
    parser.add_argument("--out", required=True, type=Path, help="destination directory")
    parser.add_argument("--cameras", type=int, default=12, help="number of cameras (default 12)")
    parser.add_argument("--points", type=int, default=500, help="number of 3D points (default 500)")
    parser.add_argument("--seed", type=int, default=0, help="RNG seed (default 0)")
    parser.add_argument("--radius", type=float, default=3.0, help="radius of the camera circle")
    parser.add_argument(
        "--height", type=float, default=1.0, help="height of the cameras above the XY plane"
    )
    parser.add_argument(
        "--arc-deg", type=float, default=360.0, help="cameras span only this arc (default 360)"
    )
    parser.add_argument(
        "--height-jitter", type=float, default=0.0, help="std-dev of per-camera height offsets"
    )
    parser.add_argument(
        "--roll-jitter-deg",
        type=float,
        default=0.0,
        help="std-dev of per-camera roll about the optical axis, degrees",
    )
    parser.add_argument(
        "--tilt-deg", type=float, default=0.0, help="rotate the whole scene by this angle"
    )
    parser.add_argument(
        "--tilt-axis",
        type=float,
        nargs=3,
        default=(1.0, 0.0, 0.0),
        metavar=("X", "Y", "Z"),
        help="axis of the tilt (default 1 0 0)",
    )
    parser.add_argument(
        "--offset",
        type=float,
        nargs=3,
        default=(0.0, 0.0, 0.0),
        metavar=("X", "Y", "Z"),
        help="translate the whole scene after the tilt",
    )
    parser.add_argument(
        "--non-planar",
        type=float,
        default=0.0,
        help="amplitude of the vertical wave height += A * sin(2 * phi)",
    )
    parser.add_argument(
        "--names-from",
        type=Path,
        default=None,
        help="the run's frames.json: image names are taken from the selected frames",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """CLI entry point."""
    args = parse_args(argv)
    if args.cameras < 1:
        raise SystemExit("--cameras must be >= 1")
    if args.points < 1:
        raise SystemExit("--points must be >= 1")

    image_names: tuple[str, ...] = ()
    if args.names_from is not None:
        payload = json.loads(args.names_from.read_text(encoding="utf-8"))
        image_names = tuple(f"{f['frame_id']}.jpg" for f in payload["frames"] if f.get("selected"))
        if not image_names:
            raise SystemExit(f"{args.names_from} has no selected frames")
        if args.cameras > len(image_names):
            raise SystemExit(
                f"{args.cameras} cameras requested, but only {len(image_names)} selected frames"
            )

    params = SceneParams(
        num_cameras=args.cameras,
        num_points=args.points,
        seed=args.seed,
        radius=args.radius,
        height=args.height,
        image_names=image_names,
        arc_deg=args.arc_deg,
        height_jitter=args.height_jitter,
        roll_jitter_deg=args.roll_jitter_deg,
        tilt_deg=args.tilt_deg,
        tilt_axis=tuple(args.tilt_axis),
        offset=tuple(args.offset),
        non_planar=args.non_planar,
    )
    info = make_scene(args.out, params)
    print(f"written: {info['sparse_dir']}")
    print(
        f"cameras: {info['num_images']}, points: {info['num_points']}, "
        f"observations: {info['num_observations']}"
    )
    print("WARNING: the scene checks only formats and geometry, not reconstruction quality.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
