"""End-to-end check of stages 1–2 on a real video (T025).

The video is generated by ffmpeg right in the test; no GPU is required. The seams between
modules are checked: file check → candidate extraction → metrics → selection → package → manifest.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

import pytest

from v3d.artifacts import REQUIRED_MANIFEST_FIELDS, RunStatus
from v3d.errors import ExitCode, NotEnoughFramesError
from v3d.package import verify_sha256sums
from v3d.prepare import run_prepare

BUDGET = 12


@pytest.fixture(scope="module")
def clip(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """A short test video: 4 seconds, 10 frames/s."""
    path = tmp_path_factory.mktemp("video") / "clip.mp4"
    subprocess.run(
        [
            "ffmpeg",
            "-loglevel",
            "error",
            "-f",
            "lavfi",
            "-i",
            "testsrc=size=320x240:rate=10:duration=4",
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
            str(path),
        ],
        check=True,
    )
    return path


def _prepare(clip: Path, out: Path, **kwargs):
    return run_prepare(clip, out_root=out, budget=BUDGET, long_side=320, **kwargs)


def test_prepare_creates_transfer_package(clip: Path, tmp_path: Path) -> None:
    """The full path of stages 1–2 ends with a built package."""
    result = _prepare(clip, tmp_path / "runs")
    selected = [r for r in result.records if r.selected]

    assert len(selected) == BUDGET, "the frame budget must be respected exactly"
    images = sorted((result.layout.package / "images").glob("*.jpg"))
    assert len(images) == BUDGET, "exactly the selected frames go into the package"
    assert (result.layout.package / "SHA256SUMS").exists()
    assert (result.layout.package / "RUN_ON_GPU.txt").exists()
    assert not (result.layout.package / "manifest.json").exists(), (
        "the manifest must not get into the transfer package"
    )


def test_package_integrity_is_checked_strictly_after_build(clip: Path, tmp_path: Path) -> None:
    """Right after the build there can be no extra files — the strict check passes."""
    result = _prepare(clip, tmp_path / "runs")
    verify_sha256sums(result.layout.package, strict=True)


def test_manifest_contains_all_required_fields(clip: Path, tmp_path: Path) -> None:
    """Without a complete manifest the run is not reproducible (FR-034)."""
    result = _prepare(clip, tmp_path / "runs")
    manifest = json.loads(result.layout.manifest.read_text(encoding="utf-8"))
    for field in REQUIRED_MANIFEST_FIELDS:
        assert field in manifest, f"the manifest lacks the required field {field}"
    assert manifest["input_video"]["sha256"], "the input must be identifiable by hash"
    assert manifest["image_transform"]["crop"] is None, "crop is not applied in v1"


def test_frame_records_cover_all_candidates(clip: Path, tmp_path: Path) -> None:
    """frames.json describes every considered frame, not only the selected ones."""
    result = _prepare(clip, tmp_path / "runs")
    frames = json.loads(result.layout.frames.read_text(encoding="utf-8"))["frames"]
    assert len(frames) == result.candidates_total
    assert all(f["timestamp_us"] is not None for f in frames), "the frame time is mandatory"
    rejected = [f for f in frames if not f["selected"]]
    assert all(f["reject_reason"] for f in rejected), "an unselected frame has a reason"


def test_metrics_are_recorded_and_not_replaced_by_zero(clip: Path, tmp_path: Path) -> None:
    """Sharpness is measured for all candidates; zero would mean a measured zero."""
    result = _prepare(clip, tmp_path / "runs")
    frames = json.loads(result.layout.frames.read_text(encoding="utf-8"))["frames"]
    assert all(f["sharpness"] is not None for f in frames)
    selected = [f for f in frames if f["selected"]]
    assert selected[0]["diff_to_prev_selected"] is None, (
        "the first frame has nothing to compare with"
    )
    assert all(f["diff_to_prev_selected"] is not None for f in selected[1:])


def test_repeat_with_same_inputs_gives_same_digest(clip: Path, tmp_path: Path) -> None:
    """Run identity is determined by the inputs, not by the launch time (FR-011)."""
    first = _prepare(clip, tmp_path / "runs_a")
    second = _prepare(clip, tmp_path / "runs_b")
    assert first.run_id.split("-")[-1] == second.run_id.split("-")[-1]
    assert [r.frame_id for r in first.records] == [r.frame_id for r in second.records]


def test_too_few_frames_leave_a_diagnosable_run(clip: Path, tmp_path: Path) -> None:
    """The package is not built, but the run is readable and marked unusable."""
    out = tmp_path / "runs"
    with pytest.raises(NotEnoughFramesError) as excinfo:
        run_prepare(clip, out_root=out, budget=4, long_side=320, min_frames=10)

    assert excinfo.value.exit_code == ExitCode.NOT_ENOUGH_FRAMES
    assert "--force" in (excinfo.value.details or ""), "a retry must be suggested"

    run_dirs = list(out.iterdir())
    assert len(run_dirs) == 1
    status = json.loads((run_dirs[0] / "normalized" / "status.json").read_text(encoding="utf-8"))
    assert status["status"] == RunStatus.FAILED.value
    assert not (run_dirs[0] / "package" / "SHA256SUMS").exists(), "the package is not built"


def test_run_directory_is_not_silently_overwritten(clip: Path, tmp_path: Path) -> None:
    """A repeat with the same inputs hits the existing directory instead of wiping it."""
    from v3d.errors import RunDirExistsError
    from v3d.runs import create_run_dir

    out = tmp_path / "runs"
    first = _prepare(clip, out)
    marker = first.layout.root / "marker.txt"
    marker.write_text("do not touch", encoding="utf-8")

    with pytest.raises(RunDirExistsError) as excinfo:
        create_run_dir(out, first.run_id, force=False)

    assert excinfo.value.exit_code == ExitCode.RUN_DIR_EXISTS
    assert marker.exists(), "foreign files are not deleted"


def test_forced_overwrite_is_recorded_in_the_run(clip: Path, tmp_path: Path) -> None:
    """--force is allowed, but the fact of the overwrite must stay in the data."""
    from v3d.runs import create_run_dir

    out = tmp_path / "runs"
    first = _prepare(clip, out)
    _, forced = create_run_dir(out, first.run_id, force=True)
    assert forced is True, "a forced overwrite must not go unnoticed"
